# Generated by Django 5.2.5 on 2025-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('CANDIDATE_REJECTED', 'Rejected by Candidate'), ('IN_REVIEW', 'In Review'), ('INTERVIEW', 'Interviewing'), ('HIRED', 'Hired'), ('EMPLOYER_REJECTED', 'Rejected by Employer')], default='APPLIED', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status_last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_candidates', models.JSONField(default=list)),
                ('notification_iteration', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_type', models.CharField(choices=[('SHORT_TERM', 'Short-Term Hire'), ('LONG_TERM', 'Long-Term Hire')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_fill_enabled', models.BooleanField(default=False)),
                ('transport_provided', models.BooleanField(default=False)),
                ('accommodation_provided', models.BooleanField(default=False)),
                ('meals_provided', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('shift_start_time', models.TimeField(blank=True, null=True)),
                ('shift_end_time', models.TimeField(blank=True, null=True)),
                ('short_term_pay_unit', models.CharField(blank=True, choices=[('PER_PATIENT', 'Per Patient'), ('PER_HOUR', 'Per Hour')], max_length=20, null=True)),
                ('short_term_pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_availability_matrix', models.JSONField(blank=True, default=list)),
                ('long_term_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_experience_years', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
