# Generated by Django 5.2.5 on 2025-08-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='filled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_jobs', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='profiles.employerprofile'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_qualifications',
            field=models.ManyToManyField(blank=True, to='profiles.degreetype'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='jobmatch',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost'),
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job_post', 'candidate')},
        ),
    ]
