# Generated by Django 5.2.5 on 2025-08-22 12:55

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR_PHOTO', 'Aadhaar Card Photo'), ('CANDIDATE_PHOTO', 'Candidate Photo'), ('EDUCATION_SUPPORT', 'Education Supporting Document'), ('LICENSURE', 'Licensure Document'), ('CERTIFICATION', 'Certification Document'), ('WORK_EXPERIENCE_SUPPORT', 'Work Experience Supporting Document')], max_length=50)),
                ('file', models.FileField(upload_to=profiles.models.get_candidate_credential_path)),
                ('url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_job_type', models.JSONField(blank=True, default=list)),
                ('weekly_availability_matrix', models.JSONField(blank=True, default=list)),
                ('pay_per_patient', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pay_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_travel_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('average_quality_score', models.FloatField(default=4.0)),
                ('is_aadhaar_verified', models.BooleanField(default=False)),
                ('is_qualification_verified', models.BooleanField(default=False)),
                ('is_skill_credential_verified', models.BooleanField(default=False)),
                ('is_experience_credential_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DegreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Diagnostic Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_graduation', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year_of_graduation'],
            },
        ),
        migrations.CreateModel(
            name='EmployerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR_PHOTO', 'Aadhaar Card Photo'), ('FACILITY_IMAGE', 'Facility Image'), ('REGISTRATION_LICENSE', 'Registration and Licenses'), ('INFRA_OPERATIONAL', 'Infrastructure and Operational Clearance'), ('QUALITY_ACCREDITATION', 'Quality and Accreditation Standard'), ('OTHER', 'Other Documentation')], max_length=50)),
                ('url', models.URLField(max_length=1024)),
                ('file', models.FileField(blank=True, null=True, upload_to=profiles.models.get_employer_credential_path)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_aadhaar_num', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('contact_num', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_address', models.TextField(blank=True, null=True)),
                ('institution_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('institution_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('institution_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('institution_website', models.URLField(blank=True, max_length=512, null=True)),
                ('outpatient_clinic', models.BooleanField(blank=True, null=True)),
                ('inpatient_facility', models.BooleanField(blank=True, null=True)),
                ('ip_bed_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('emd_room', models.BooleanField(blank=True, null=True)),
                ('emd_bed_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('icu_facilities', models.BooleanField(blank=True, null=True)),
                ('icu_bed_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('nicupicu', models.BooleanField(blank=True, null=True)),
                ('nicupicu_bed_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('otroom', models.BooleanField(blank=True, null=True)),
                ('otroom_bed_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('diag_lab', models.BooleanField(blank=True, null=True)),
                ('radio_lab', models.BooleanField(blank=True, null=True)),
                ('pharmacy', models.BooleanField(blank=True, null=True)),
                ('security', models.BooleanField(blank=True, null=True)),
                ('employed_doctors_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('employed_nurses_num', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('average_quality_score', models.FloatField(default=4.0)),
                ('is_aadhaar_verified', models.BooleanField(default=False)),
                ('is_credential_verified', models.BooleanField(default=False)),
                ('job_post_quota', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Radiology Facilities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Specialities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('institution_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
