# Generated by Django 5.2.5 on 2025-08-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatecredential',
            name='candidate_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='candidate_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='education',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.country'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.degreetype'),
        ),
        migrations.AddField(
            model_name='candidatecredential',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents', to='profiles.education'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='diag_lab_facilities',
            field=models.ManyToManyField(blank=True, to='profiles.diagnosticfacility'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employercredential',
            name='employer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='profiles.employerprofile'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='institution_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.institutiontype'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='radio_lab_facilities',
            field=models.ManyToManyField(blank=True, to='profiles.radiologyfacility'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='candidatecredential',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='profiles.skill'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='profiles.speciality'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='profiles.speciality'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='candidate_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='profiles.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidatecredential',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_documents', to='profiles.workexperience'),
        ),
    ]
