# Generated by Django 5.2.5 on 2025-08-22 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='candidatefeedback',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_feedback', to='jobs.jobpost'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='job_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jobs.jobpost'),
        ),
    ]
